---
# Variables can be set from the shell: `DOCKERTAG=foo docker-compose build`
# or from a .env file. See docker-compose documentation for details
# Variable DOCKERUSER should be set to your dockerhub user
# Alternatively, use a docker registry url as the image name
version: '3.7'
services:
  ## Image runtime service
  ## This can be used to add volume mounts or pass environment variables
  ## Todo: make a service which can use the container interactively
  detectron:
    container_name: detectron
#    build:
#      context: .
#      dockerfile: Dockerfile
#    working_dir: "${DATA_MOUNT}"
    image: "edgarrt/detectron-custom:1.1"
    tty: true
    volumes:
      - "${DATA_MOUNT}:${DATA_MOUNT}"
    environment:
      DATA_MOUNT: "${DATA_MOUNT}"
    command: ["bash"]

...
